---
# - name: Verificar OS
#   fail:  msg="This role is not supported in {{ansible_os_family}} OS"
#   when: ansible_os_family != "Debian"

- name: Get info about vms
  virt:
   command: info
  register: aux_info
  tags: always

# ok: [localhost] => (item={'key': 'debian10', 'value': {'state': 'shutdown', 'maxMem': '1048576', 'memory': '1048576', 'nrVirtCpu': 2, 'cpuTime': '0', 'autostart': 0}})

- name: Create list with information about vms
  set_fact:
    kvm_info: "{{ kvm_info|default([]) + [ { \
                  'name': item.key, \
                  'state': item.value.state, \
                  'maxMem': item.value.maxMem, \
                  'memory': item.value.memory, \
                  'nrVirtCpu': item.value.nrVirtCpu, \
                  'cpuTime': item.value.cpuTime, \
                  'autostart': item.value.autostart \
                  } ] }}"
  with_dict: "{{ aux_info }}"
  when:
    - item.key != 'changed'
    - item.key != 'failed'
  tags: always

# kvm_vms_info => é utilizada na app para 'sacar' a info sobre as vms
- name: kvm_vms_info # do not change!
  debug:
    var: kvm_info
  tags: always
